---
- import_playbook: variable-check.yml
  vars:
    playbook: server.yml

- name: Test Connection and Determine Remote User
  hosts: web:&{{ env }}
  gather_facts: false
  roles:
    - { role: connection, tags: [connection, always] }

- name: Set ansible_python_interpreter
  hosts: web:&{{ env }}
  gather_facts: false
  become: yes
  roles:
    - { role: python_interpreter, tags: [always] }

- name: WordPress Server - Install LEMP Stack with PHP 7.4 and MariaDB MySQL
  hosts: web:&{{ env }}
  become: yes
  roles:
    - { role: common, tags: [common] }
    - { role: swapfile, swapfile_size: 1GB, swapfile_file: /swapfile, tags: [swapfile] }
    - { role: fail2ban, tags: [fail2ban] }
    - { role: ferm, tags: [ferm] }
    - { role: ntp, tags: [ntp] }
    - { role: users, tags: [users] }
    - { role: sshd, tags: [sshd] }
    - { role: mariadb, tags: [mariadb] }
    - { role: ssmtp, tags: [ssmtp, mail] }
    - { role: php, tags: [php] }
    - { role: memcached, tags: [memcached] }
    - { role: nginx, tags: [nginx] }
    - { role: logrotate, tags: [logrotate] }
    - { role: composer, tags: [composer] }
    - { role: wp-cli, tags: [wp-cli] }
    - { role: letsencrypt, tags: [letsencrypt], when: sites_using_letsencrypt | count }
    - { role: wordpress-setup, tags: [wordpress, wordpress-setup, letsencrypt] }

- name: Setup unattended-upgrades
  hosts: web:&{{ env }}
  become: yes
  roles:
  - role: unattended
    unattended_mail: "{{ mail_admin }}"
    unattended_mail_only_on_error: true
    unattended_automatic_reboot: true
    unattended_automatic_reboot_time: "05:{{ 60 | random }}"
    unattended_remove_unused_dependencies: true
    tags: [upgrades]