---
- name: Create WP backups directory
  file:
    path: "{{ www_root }}/{{ item.key }}/backups"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory
  with_dict: "{{ wordpress_sites }}"

- name: Setup MAILTO on WP cron
  cronvar:
    name: MAILTO
    value: "{{ item.value.cron_mailto | default(mail_admin) }}"
    cron_file: "wordpress-{{ item.key | replace('.', '_') }}"
  with_dict: "{{ wordpress_sites }}"

- name: Setup WP WooCommerce maintenance cron
  cron:
    name: "{{ item.key }} WooCommerce maintenance"
    hour: "4"
    minute: "0"
    user: "{{ web_user }}"
    job: >
      cd {{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }} &&
      wp wc tool run verify_db_tables --user=admin.creame --quiet &&
      wp wc tool run clear_expired_transients --user=admin.creame --quiet &&
      wp wc tool run delete_orphaned_variations --user=admin.creame --quiet &&
      wp wc tool run clear_expired_download_permissions --user=admin.creame --quiet &&
      wp wc tool run recount_terms --user=admin.creame --quiet &&
      wp wc tool run regenerate_product_lookup_tables --user=admin.creame --quiet
    cron_file: "wordpress-{{ item.key | replace('.', '_') }}"
  with_dict: "{{ wordpress_sites }}"
  when: item.value.woocommerce | default(false)

- name: Setup WP DB optimize cron
  cron:
    name: "{{ item.key }} WordPress BD optimize"
    hour: "4"
    minute: "10"
    user: "{{ web_user }}"
    job: >
      cd {{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }} &&
      wp transient delete --expired --quiet &&
      wp db optimize > /dev/null
    cron_file: "wordpress-{{ item.key | replace('.', '_') }}"
  with_dict: "{{ wordpress_sites }}"

- name: Setup WP DB backup cron
  cron:
    name: "{{ item.key }} WordPress BD backup"
    hour: "4"
    minute: "15"
    user: "{{ web_user }}"
    job: >
      cd {{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }} &&
      wp db export - | gzip > {{ www_root }}/{{ item.key }}/backups/backup-`date +\%Y\%m\%dT\%H\%M\%S`.sql.gz
    cron_file: "wordpress-{{ item.key | replace('.', '_') }}"
  with_dict: "{{ wordpress_sites }}"

- name: Setup WP security updates cron
  cron:
    name: "{{ item.key }} WordPress security updates"
    hour: "4"
    minute: "20"
    user: "{{ web_user }}"
    job: >
      cd {{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }} &&
      wp core update --minor --quiet &&
      wp core update-db --quiet
    cron_file: "wordpress-{{ item.key | replace('.', '_') }}"
  with_dict: "{{ wordpress_sites }}"

- name: Setup WP languages updates cron
  cron:
    name: "{{ item.key }} WordPress languages updates"
    hour: "4"
    minute: "25"
    user: "{{ web_user }}"
    job: >
      cd {{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }} &&
      wp language core update >/dev/null 2>&1 &&
      wp language plugin update --all >/dev/null 2>&1
    cron_file: "wordpress-{{ item.key | replace('.', '_') }}"
  with_dict: "{{ wordpress_sites }}"

- name: Setup Verify checksums cron
  cron:
    name: "{{ item.key }} WordPress verify checksums"
    hour: "4"
    minute: "30"
    user: "{{ web_user }}"
    job: >
      cd {{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }} &&
      wp core verify-checksums --quiet
    cron_file: "wordpress-{{ item.key | replace('.', '_') }}"
  with_dict: "{{ wordpress_sites }}"

- name: Setup Image optimization cron
  cron:
    name: "{{ item.key }} image optimization"
    hour: "1"
    minute: "5"
    user: "{{ web_user }}"
    job: >
      cd {{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }}/web/app/uploads &&
      find -type f -iname "*.jpg"  -mtime -1 -daystart -exec jpegoptim -qsp {} \; &&
      find -type f -iname "*.jpeg" -mtime -1 -daystart -exec jpegoptim -qsp {} \; &&
      find -type f -iname "*.png"  -mtime -1 -daystart -exec optipng -quiet -o5 -preserve -strip all {} \;
    cron_file: "wordpress-{{ item.key | replace('.', '_') }}"
  with_dict: "{{ wordpress_sites }}"
  when: image_optimize | default(false)

- name: Setup WebP conversion cron
  cron:
    name: "{{ item.key }} WebP conversion"
    hour: "2"
    minute: "5"
    user: "{{ web_user }}"
    job: >
      cd {{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }}/web/app/uploads &&
      find -type f -iname "*.jpg"  -mtime -1 -daystart -exec sh -c 'cwebp -quiet -q 80 $1 -o "$1.webp"' _ {} \; &&
      find -type f -iname "*.jpeg" -mtime -1 -daystart -exec sh -c 'cwebp -quiet -q 80 $1 -o "$1.webp"' _ {} \; &&
      find -type f -iname "*.png"  -mtime -1 -daystart -exec sh -c 'cwebp -quiet -lossless $1 -o "$1.webp"' _ {} \;
    cron_file: "wordpress-{{ item.key | replace('.', '_') }}"
  with_dict: "{{ wordpress_sites }}"
  when: image_optimize | default(false)
