---
- name: Create WP backups directory
  file:
    path: "{{ www_root }}/{{ item.key }}/backups"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory
  with_dict: "{{ wordpress_sites }}"

- name: Setup WP Woocommerce maintenance cron
  cron:
    name: "{{ item.key }} Woocommerce maintenance cron"
    hour: "4"
    minute: "1"
    user: "{{ web_user }}"
    job: >
      cd {{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }} &&
      wp wc tool run clear_expired_transients --user=admin.creame &&
      wp wc tool run delete_orphaned_variations --user=admin.creame &&
      wp wc tool run clear_expired_download_permissions --user=admin.creame &&
      wp wc tool run recount_terms --user=admin.creame &&
      wp wc tool run add_order_indexes --user=admin.creame &&
      wp wc tool run regenerate_product_lookup_tables --user=admin.creame
    cron_file: "wordpress-{{ item.key | replace('.', '_') }}"
  with_dict: "{{ wordpress_sites }}"
  when: item.value.woocommerce | default(false)

- name: Setup WP DB backup cron
  cron:
    name: "{{ item.key }} WordPress BD backup cron"
    hour: "4"
    minute: "15"
    user: "{{ web_user }}"
    job: >
      cd {{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }} &&
      wp transient delete --expired &&
      wp db optimize &&
      wp db export - | gzip > {{ www_root }}/{{ item.key }}/backups/backup-`date +\%Y\%m\%dT\%H\%M\%S`.sql.gz
    cron_file: "wordpress-{{ item.key | replace('.', '_') }}"
  with_dict: "{{ wordpress_sites }}"

- name: Setup WP security updates cron
  cron:
    name: "{{ item.key }} WordPress minor updates cron"
    hour: "4"
    minute: "20"
    user: "{{ web_user }}"
    job: >
      cd {{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }} &&
      wp core update --minor &&
      wp core update-db &&
      wp core language update
    cron_file: "wordpress-{{ item.key | replace('.', '_') }}"
  with_dict: "{{ wordpress_sites }}"

- name: Setup Image optimization cron
  cron:
    name: "{{ item.key }} image optimization cron"
    hour: "1"
    minute: "5"
    user: "{{ web_user }}"
    job: >
      cd {{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }}/web/app/uploads &&
      find -type f -name "*.jpg" -mtime -1 -daystart -exec jpegoptim -qs {} \; &&
      find -type f -name "*.jpg" -mtime -1 -daystart -exec sh -c 'cwebp -quiet -q 80 $1 -o "${1%.jpg}.webp"' _ {} \; &&
      find -type f -name "*.png" -mtime -1 -daystart -exec optipng  -quiet -o4 -strip all {} \; &&
      find -type f -name "*.png" -mtime -1 -daystart -exec sh -c 'cwebp -quiet -lossless $1 -o "${1%.png}.webp"' _ {} \;
    cron_file: "wordpress-images-{{ item.key | replace('.', '_') }}"
  with_dict: "{{ wordpress_sites }}"
  when: image_optimize | default(false)
