---
- name: Create WP backups directory
  file:
    path: "{{ www_root }}/{{ item.key }}/backups"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory
  with_dict: "{{ wordpress_sites }}"

- name: Setup WP DB backup cron
  cron:
    name: "{{ item.key }} WordPress BD backup cron"
    hour: "4"
    minute: "0"
    user: "{{ web_user }}"
    job: >
      cd {{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }} &&
      wp db optimize &&
      wp db export {{ www_root }}/{{ item.key }}/backups/backup-`date +\%Y\%m\%dT\%H\%M\%S`.sql
    cron_file: "wordpress-{{ item.key | replace('.', '_') }}"
  with_dict: "{{ wordpress_sites }}"

- name: Setup WP security updates cron
  cron:
    name: "{{ item.key }} WordPress minor updates cron"
    hour: "4"
    minute: "10"
    user: "{{ web_user }}"
    job: >
      cd {{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }} &&
      wp core update --minor &&
      wp core update-db &&
      wp core language update
    cron_file: "wordpress-{{ item.key | replace('.', '_') }}"
  with_dict: "{{ wordpress_sites }}"
