composer_keep_updated: true
composer_global_packages:
 - { name: hirak/prestissimo }
apt_cache_valid_time: 3600
apt_package_state: present
apt_security_package_state: latest
apt_dev_package_state: latest
apt_packages_custom:
  jpegoptim: "{{ apt_package_state }}"
  optipng: "{{ apt_package_state }}"
  webp: "{{ apt_package_state }}"
ntp_timezone: Etc/UTC
ntp_manage_config: true
www_root: /srv/www
ip_whitelist:
  - "{{ (env == 'development') | ternary(ansible_default_ipv4.gateway, ipify_public_ip | default('')) }}"
nginx_conf: nginx-includes/nginx.conf.child
nginx_wordpress_site_conf: nginx-includes/wordpress-site.conf.child
php_memory_limit: 256M
# php_extensions_custom:
#   php7.3-soap: "{{ apt_package_state }}"
wp_cli_packages:
  - wp-cli/doctor-command
  - wp-cli/profile-command
# Disable wp option update releases path on deploy
update_wp_theme_paths: false
# Enable image optimization cron task and serve webp format
image_optimize: true

# Custom deploy hooks
deploy_initialize_after:
  - "{{ playbook_dir }}/deploy-hooks/initialize-after.yml"
deploy_build_after:
  - "{{ playbook_dir }}/deploy-hooks/build-after.yml"
  - "{{ playbook_dir }}/roles/deploy/hooks/build-after.yml"
deploy_finalize_after:
  - "{{ playbook_dir }}/deploy-hooks/finalize-after-install.yml"
  - "{{ playbook_dir }}/deploy-hooks/finalize-after.yml"

# Custom shared children
project_shared_children:
  - path: web/app/uploads
    src: uploads
  - path: web/app/cache
    src: cache

# Values of raw_vars will be wrapped in `{% raw %}` to avoid templating problems if values include `{%` and `{{`.
# Will recurse dicts/lists. `*` is wildcard for one or more dict keys, list indices, or strings. Example:
#   - vault_wordpress_sites.*.*_salt    -- matches vault_wordpress_sites.example.com.env.secure_auth_salt etc.
# Will not function for var names or topmost dict keys that contain a period ('.').
raw_vars:
  - vault_mail_password
  - vault_mysql_root_password
  - vault_users.*.password
  - vault_users.*.salt
  - vault_wordpress_env_defaults
  - vault_wordpress_sites
