apt_cache_valid_time: 3600
apt_package_state: present
apt_security_package_state: latest
apt_dev_package_state: latest
apt_packages_custom:
  jpegoptim: "{{ apt_package_state }}"
  optipng: "{{ apt_package_state }}"
  webp: "{{ apt_package_state }}"
composer_keep_updated: true
ntp_timezone: Etc/UTC
ntp_manage_config: true
www_root: /srv/www
max_journal_size: 512M

letsencrypt_contact_emails:
  - "{{ mail_admin }}"

# Nginx
nginx_wordpress_site_conf: nginx-includes/wordpress-site.conf.child
nginx_skip_cache_cookie: comment_author|wordpress_[a-f0-9]+|wp-postpass|wordpress_no_cache|wordpress_logged_in|woocommerce_[a-z0-9_]+
nginx_hsts_include_subdomains: true

h5bp_expires_enabled: true

# PHP
php_version: "8.2"
php_memory_limit: 256M
php_error_reporting: "E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE & ~E_WARNING"
php_extensions_custom:
  php8.2-soap: "{{ apt_package_state }}"
  php8.2-gd: "{{ apt_package_state }}"

# WP-Cli
# wp_cli_packages:
#   - wp-cli/doctor-command
#   - wp-cli/profile-command
#   - aaemnnosttv/wp-cli-login-command
#   - mahi-mahi/wp-cli-test-email

# Disable wp option update releases path on deploy
update_wp_theme_paths: false

# Enable image optimization cron task and serve webp format
image_optimize: true
# image_to_webp: true

# WordPress languages (others than default en_US)
project_languages:
  - es_ES

# Custom deploy hooks
deploy_initialize_after:
  - "{{ playbook_dir }}/deploy-hooks/initialize-after.yml"
deploy_finalize_after:
  - "{{ playbook_dir }}/deploy-hooks/finalize-after.yml"
  - "{{ playbook_dir }}/deploy-hooks/finalize-after-language.yml"

# Custom shared children
project_shared_children:
  - path: web/app/uploads
    src: uploads
  - path: web/app/cache
    src: cache

# Custom copy folders
project_copy_folders:
  - vendor
  - web/app/languages

# Values of raw_vars will be wrapped in `{% raw %}` to avoid templating problems if values include `{%` and `{{`.
# Will recurse dicts/lists. `*` is wildcard for one or more dict keys, list indices, or strings. Example:
#   - vault_wordpress_sites.*.*_salt    -- matches vault_wordpress_sites.example.com.env.secure_auth_salt etc.
# Will not function for var names or topmost dict keys that contain a period ('.').
raw_vars:
  - vault_mail_password
  - vault_mysql_root_password
  - vault_users.*.password
  - vault_users.*.salt
  - vault_wordpress_env_defaults
  - vault_wordpress_sites
